apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
data:
  # ðŸŒ‰ Bridge Mode: Lets K8s talk to your Docker Desktop Postgres
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "ticketmaster"
  DB_USER: "postgres"
  # Same for Redis
  REDIS_ADDR: "host.docker.internal:6379"