apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  type: LoadBalancer
  selector:
    app: ticket-api
  ports:
    - protocol: TCP
      port: 80            # You visit http://localhost
      targetPort: 8080    # Container port